### ISSUE TITLE
identifier "MAX_FACTOR" and "POWER_BETA" is undefined

### ISSUE THREAD

**Issue by UmbertoCorvaglia** [Ljiee/deepfuzz#1]
MacBookUser:deepfuzz-master User$ make
[*] Checking for the ability to compile x86 code...
[+] Everything seems to be working, ready to compile.
cc -O3 -funroll-loops -Wall -D_FORTIFY_SOURCE=2 -g -Wno-pointer-sign -DAFL_PATH=\"/usr/local/lib/afl\" -DDOC_PATH=\"/usr/local/share/doc/afl\" -DBIN_PATH=\"/usr/local/bin\" afl-gcc.c -o afl-gcc 
set -e; for i in afl-g++ afl-clang afl-clang++; do ln -sf afl-gcc $i; done
cc -O3 -funroll-loops -Wall -D_FORTIFY_SOURCE=2 -g -Wno-pointer-sign -DAFL_PATH=\"/usr/local/lib/afl\" -DDOC_PATH=\"/usr/local/share/doc/afl\" -DBIN_PATH=\"/usr/local/bin\" afl-fuzz.c -o afl-fuzz 
afl-fuzz.c:5384:18: error: use of undeclared identifier 'MAX_FACTOR'
        factor = MAX_FACTOR / next_p264(min_hit_cnt);
                 ^
afl-fuzz.c:5388:16: error: use of undeclared identifier 'MAX_FACTOR'
  if (factor > MAX_FACTOR) 
               ^
afl-fuzz.c:5389:14: error: use of undeclared identifier 'MAX_FACTOR'
    factor = MAX_FACTOR;
             ^
afl-fuzz.c:5391:14: error: use of undeclared identifier 'POWER_BETA'
    factor = POWER_BETA;
             ^
afl-fuzz.c:5394:26: error: use of undeclared identifier 'POWER_BETA'
  perf_score *= factor / POWER_BETA;
                         ^
5 errors generated.
make: *** [afl-fuzz] Error 1

**Comment by Ljiee** [comment]
Thank you, it has been fixed.
